# Generated by Django 2.2.16 on 2021-11-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('m', 'moderator'), ('a', 'admin'), ('u', 'user')], default='user', max_length=20, verbose_name='Статус'),
        ),
    ]
