# Generated by Django 2.2.16 on 2021-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211203_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'moderator'), ('admin', 'admin'), ('user', 'user')], max_length=20, verbose_name='Статус пользователя'),
        ),
    ]
