# Generated by Django 2.2.16 on 2021-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211203_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('moderator', 'moderator'), ('admin', 'admin'), ('user', 'user')], max_length=20, null=True, verbose_name='Статус пользователя'),
        ),
    ]
