# Generated by Django 2.2.16 on 2021-12-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20211203_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='release',
            new_name='year',
        ),
    ]
