# Generated by Django 2.2.16 on 2021-12-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20211206_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('m', 'moderator'), ('u', 'user')], default='u', max_length=20, verbose_name='Статус пользователя'),
        ),
    ]
